agent_templates:
    simple_assistant: &simple_assistant
        architecture: SimpleChatbot
        model_settings: *openai_gpt4o
        role: assistant

    synthetic_user: &synthetic_user
        architecture: SimpleChatbot
        model_settings: *mythomax
        role: user

    