model_templates:
    groq_llama3: &groq_llama3 # model spec
        model: groq/llama3-8b-8192
        api_key: GROQ_API_KEY
        hyperparams:
            temperature: 0.9

    openai_gpt4o: &openai_gpt4o
        model: openai/gpt-4o
        api_key: OPENAI_API_KEY

    claude_sonnet35: &claude_sonnet35
        model: anthropic/claude-3-5-sonnet-20240620
        api_key: CLAUDE_API_KEY
        hyperparams:
            temperature: 0

    groq_gemma7b: &groq_gemma7b
        model: groq/gemma-7b-it
        api_key: GROQ_API_KEY
        hyperparams:
            temperature: 0

    mythomax: &mythomax
        model: openrouter/gryphe/mythomax-l2-13b:nitro
        api_key: OPENROUTER_API_KEY
